name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - working-directory: server
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check --verbose
    
